andre = User.create(name: 'Andre')
bart = User.create(name: 'Bart')
dries = User.create(name: 'Dries')
elger = User.create(name: 'Elger')
emiel = User.create(name: 'Emiel')
frans = User.create(name: 'Frans')
gemma = User.create(name: 'Gemma')
gregg = User.create(name: 'Gregg')
hay = User.create(name: 'Hay')
heinze = User.create(name: 'Heinze')
herve = User.create(name: 'Herve')
inge = User.create(name: 'Inge')
jeroen = User.create(name: 'Jeroen')
joel = User.create(name: 'Joel')
joost = User.create(name: 'Joost')
lotte = User.create(name: 'Lotte')
marcel = User.create(name: 'Marcel')
martijn = User.create(name: 'Martijn')
mireille = User.create(name: 'Mireille')
niall = User.create(name: 'Niall')
nienke = User.create(name: 'Nienke')
sebastiaan = User.create(name: 'Sebastiaan')
tim = User.create(name: 'Tim')

story = Story.new
story.aspects << TextAspect.new(aspect: :what, text: 'Huge party', order: 1)
story.aspects << TextAspect.new(aspect: :who, text: 'At a hackathon', order: 2, unlocker: elger)
story.aspects << TextAspect.new(aspect: :where, text: 'Amsterdam', order: 3, unlocker: joost)
story.aspects << TextAspect.new(aspect: :when, text: 'Friday, February 6th')
story.aspects << TextAspect.new(aspect: :why, text: 'Because everyone felt like it')
story.save!